# -*- coding: utf-8 -*-
"""Task2_NLP_Chatbot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jjMmUmSVCIG6a9pGwLet5jbXNLTZ-sfB
"""

import random
import pickle
import nltk
import numpy as np
import matplotlib.pyplot as plt

from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics.pairwise import cosine_similarity
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, ConfusionMatrixDisplay

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')

knowledge_base = {
    "greeting": {
        "patterns": [
            "hi","hello","hey","good morning","good evening",
            "how are you","hiya","hey there","greetings",
            "nice to meet you","what's up","good day",
            "hello there","hi chatbot","hey bot"
        ],
        "responses": [
            "Hello!",
            "Hi there!",
            "Greetings!",
            "Nice to meet you!"
        ]
    },

    "faq": {
        "patterns": [
            "what is machine learning",
            "define machine learning",
            "what is ai",
            "define artificial intelligence",
            "what is deep learning",
            "difference between ai and ml",
            "what is data science",
            "explain neural networks",
            "what is supervised learning",
            "what is unsupervised learning",
            "what is python",
            "why use python",
            "what is nlp",
            "explain natural language processing",
            "what is chatbot"
        ],
        "responses": [
            "Machine Learning enables computers to learn from data.",
            "AI is the simulation of human intelligence by machines.",
            "NLP allows computers to understand human language."
        ]
    },

    "complaint": {
        "patterns": [
            "service is bad",
            "i am unhappy",
            "not satisfied",
            "poor support",
            "this is frustrating",
            "i have a complaint",
            "your answer is wrong",
            "bad experience",
            "i am disappointed",
            "this does not work",
            "very slow response",
            "terrible service",
            "i am angry",
            "this system failed",
            "not helpful"
        ],
        "responses": [
            "I apologize for the inconvenience.",
            "Thank you for your feedback.",
            "I understand your concern."
        ]
    },

    "farewell": {
        "patterns": [
            "bye",
            "goodbye",
            "see you later",
            "take care",
            "have a nice day",
            "quit",
            "exit",
            "catch you later",
            "bye bye",
            "see you",
            "talk later",
            "farewell",
            "good night",
            "i am leaving",
            "end chat"
        ],
        "responses": [
            "Goodbye!",
            "See you later!",
            "Have a great day!"
        ]
    }
}

lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words("english"))

def advanced_preprocess(text):
    tokens = word_tokenize(text.lower())

    processed = []

    for word in tokens:
        if word.isalpha() and word not in stop_words:
            processed.append(lemmatizer.lemmatize(word))

    return " ".join(processed)

X = []
y = []

for intent, data in knowledge_base.items():
    for pattern in data["patterns"]:
        X.append(advanced_preprocess(pattern))
        y.append(intent)

print("Total Training Samples:", len(X))

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

vectorizer = TfidfVectorizer()

X_train_tfidf = vectorizer.fit_transform(X_train)
X_test_tfidf = vectorizer.transform(X_test)

model = LogisticRegression(max_iter=1000)

model.fit(X_train_tfidf, y_train)

predictions = model.predict(X_test_tfidf)

accuracy = accuracy_score(y_test, predictions)

print("Accuracy:", round(accuracy * 100, 2), "%")

cm = confusion_matrix(y_test, predictions)

disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=model.classes_
)

disp.plot()
plt.title("Intent Classification Confusion Matrix")
plt.savefig("confusion_matrix.png")
plt.show()

print("Confusion Matrix saved as confusion_matrix.png")

all_patterns = X
all_pattern_vectors = vectorizer.transform(all_patterns)

def predict_intent_cosine(user_text):
    processed = advanced_preprocess(user_text)

    user_vector = vectorizer.transform([processed])

    similarities = cosine_similarity(
        user_vector,
        all_pattern_vectors
    )

    best_index = np.argmax(similarities)

    return y[best_index]

test_sentences = [
    "hey buddy",
    "can you explain AI",
    "your support is terrible",
    "I will talk to you later",
    "tell me about machine learning"
]

print("\nTesting Cosine Similarity Predictions\n")

for sentence in test_sentences:
    predicted = predict_intent_cosine(sentence)
    print(sentence, "-->", predicted)

with open("intent_model.pkl", "wb") as f:
    pickle.dump(
        {
            "model": model,
            "vectorizer": vectorizer,
            "knowledge_base": knowledge_base
        },
        f
    )

print("\nModel saved as intent_model.pkl")

def load_model(filename="intent_model.pkl"):
    with open(filename, "rb") as f:
        return pickle.load(f)

loaded_model = load_model()

print("Model loaded successfully")

print("\n===== NLP CHATBOT =====")

while True:

    user_input = input("\nYou: ")

    intent = predict_intent_cosine(user_input)

    print(f"[NLP detected intent] -> {intent}")

    if intent == "farewell":
        response = random.choice(
            knowledge_base[intent]["responses"]
        )
        print("Bot:", response)
        break

    elif intent in knowledge_base:
        response = random.choice(
            knowledge_base[intent]["responses"]
        )
        print("Bot:", response)

    else:
        print("Bot: Sorry, I don't understand that.")